'use client'
import './globals.css'
import { useState } from 'react'
import { Context, ModeContext } from '@/context/index.js'
import { ListItems } from '@/data/types/List'


const metadata = {
  title: 'List',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const [users,setUsers]=useState<ListItems[]>([]);//бд
  const [white,setWhite]=useState<boolean>(false);//белая/черная темы
  return (
    <html lang="en">
        <body>
        <Context.Provider value={{users,setUsers}}>
        <ModeContext.Provider value={{white,setWhite}}>
          {children}
          </ModeContext.Provider>
          </Context.Provider>
        </body>
    </html>
  )
}
