'use client'
import './globals.css'
import { List } from '@/data/List'
import { useState } from 'react'
import { ModeContext } from '@/context/index.js'
import { ListItems } from '@/data/types/List'


const metadata = {
  title: 'List',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  //const [users,setUsers]=useState<ListItems[]>([]);
  const [white,setWhite]=useState(false)
  return (
    <html lang="en">
        <body>
        {//<Context.Provider value={{users,setUsers}}>
        }
        <ModeContext.Provider value={{white,setWhite}}>
          {children}
          </ModeContext.Provider>
          {//</Context.Provider>
          }
        </body>
    </html>
  )
}
