'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import { List } from '@/data/List'
import { useState } from 'react'
//import { Context } from '@/context/index.js'
import { ListItems } from '@/data/types/List'

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'List',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  //const [users,setUsers]=useState<ListItems[]>([]);
  return (
    <html lang="en">
        <body className={inter.className}>
        {//<Context.Provider value={{users,setUsers}}>
        }
          {children}
          {//</Context.Provider>
          }
        </body>
    </html>
  )
}
